import { Award, MapPin, ShowerHead, Tent, Users, CalendarDays, Bath, Clock, CircleDot } from 'lucide-react';

const activities = [
  { number:'01', title:'Your court. Your crew.', label:'COURT RENTALS', text:'Bring your friends and make time for a few good games.', rate:'Hourly rate to be announced', href:'#rates', action:'View rental details' },
  { number:'02', title:'Meet your next doubles partner.', label:'OPEN PLAY', text:'A place to meet other players and share the court.', rate:'Sessions and player limits to be announced', href:'#schedule', action:'See the schedule' },
  { number:'03', title:'Build a better game.', label:'LESSONS & COACHING', text:'Learn with our RPO Pickleball Level 1 certified team.', rate:'Lesson formats and rates to be announced', href:'#coaching', action:'Meet the team' },
];
export default function Home() {
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <header className="header"><a className="brand" href="#" aria-label="Pondview home"><img src="/images/pondview-symbol.png" alt="Pondview Pickleball Court logo"/><span>PONDVIEW<small>PICKLEBALL COURT</small></span></a><nav aria-label="Main navigation"><a href="#play">Play</a><a href="#coaching">Coaching</a><a href="#facility">The facility</a><a href="#visit">Visit us</a></nav><a className="button small" href="#rates">Plan your play</a></header>
  <main id="main">
   <section className="hero">
    <div className="hero-photo"><img src="/images/equipment.jpg" alt="Pickleball training equipment beside the pond at Pondview" fetchPriority="high"/></div>
    <div className="hero-shade"/>
    <div className="hero-copy wrap"><p className="eyebrow"><span/> IBA, ZAMBALES · PHILIPPINES</p><h1>Rally.<br/>Recharge.<br/><em>Repeat.</em></h1><p className="hero-description">Find your rhythm at Pondview.<br/>Pickleball, good company, and a little room to unwind.</p><div className="actions"><a className="button" href="#play">Find your way to play</a><a className="text-link" href="#facility">Explore Pondview</a></div></div>
    <div className="hero-bottom wrap"><span><Award size={20}/> RPO Pickleball Level 1 certified</span><span className="photo-caption">A glimpse of life at Pondview</span></div>
   </section>
   <div className="amenity-strip"><span><ShowerHead/> On-site showers</span><span><Bath/> Bathroom facilities</span><span><Tent/> Shaded awning tent</span><span><CircleDot/> On-site training equipment</span></div>
   <section className="section wrap" id="play"><div className="section-heading"><div><p className="eyebrow">MAKE TIME FOR THE GAME</p><h2>A place for your<br/><em>kind of play.</em></h2></div><p>First rally or your favorite weekly ritual.<br/>Discover what’s taking shape at Pondview.</p></div><div className="play-grid">{activities.map(a=><article className="play-card" key={a.number}><div className="card-top"><span>{a.number}</span><span className="eyebrow">{a.label}</span></div><h3>{a.title}</h3><p>{a.text}</p><div className="card-bottom"><small>{a.rate}</small><a className="text-link" href={a.href}>{a.action}</a></div></article>)}</div></section>
   <section className="coaching-section" id="coaching"><div className="wrap coaching-grid"><figure className="team-photo"><img src="/images/team.jpg" alt="Pondview representatives holding the club banner at the RPO training class" loading="lazy"/><figcaption>Pondview represented at RPO training</figcaption></figure><div className="coaching-copy"><p className="eyebrow">A STRONG FOUNDATION</p><h2>Passion for play.<br/><em>Commitment to learning.</em></h2><div className="certification"><Award size={32}/><div><strong>RPO Pickleball</strong><span>Level 1 certified</span></div></div><p>Our team brings RPO Pickleball Level 1 certification to Pondview, with a shared passion for helping more people enjoy the game.</p><p>New to pickleball? Start with the fundamentals and grow your confidence, one rally at a time.</p><a href="#schedule" className="button outline">Explore upcoming sessions</a></div></div><figure className="class-photo wrap"><img src="/images/class.jpg" alt="Participants and instructors in the RPO pickleball training class" loading="lazy"/><figcaption>Learning together. The RPO class community.</figcaption></figure></section>
   <section className="section wrap" id="facility"><div className="section-heading"><div><p className="eyebrow">BEYOND THE BASELINE</p><h2>Play. Take a breath.<br/><em>Stay a little longer.</em></h2></div><p>Practical comforts that make<br/>your time on site more enjoyable.</p></div><div className="facility-grid"><figure className="equipment-photo"><img src="/images/equipment.jpg" alt="Pondview’s current equipment including practice balls, a dink board, training targets, paddles, and a net" loading="lazy"/><figcaption>Our current on-site equipment</figcaption></figure><div className="amenities">{[{icon:ShowerHead,title:'Refresh after your game',text:'On-site shower facilities for a fresh start after a session.'},{icon:Bath,title:'Bathroom facilities',text:'On-site bathrooms for your visit.'},{icon:Tent,title:'A shaded place to recharge',text:'Take a break from the sun under our shaded awning tent.'},{icon:CircleDot,title:'More ways to practice',text:'On-site training equipment, including a dink board, practice balls, and targets. Usage details to be announced.'}].map(x=><div className="amenity" key={x.title}><x.icon/><div><h3>{x.title}</h3><p>{x.text}</p></div></div>)}</div></div></section>
   <section className="rates-section" id="rates"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">PLAN YOUR PLAY</p><h2>Good games.<br/><em>Clear details.</em></h2></div><p>We’re putting the finishing touches on<br/>our rates and reservation information.</p></div><div className="rates-grid"><div className="rate"><span>PRIVATE COURT RENTAL</span><h3>Rates coming soon</h3><p>Hourly pricing, booking duration, and equipment inclusions will be listed here.</p></div><div className="rate"><span>OPEN PLAY</span><h3>Details coming soon</h3><p>Per-player pricing, skill groups, and session capacity will be listed here.</p></div><div className="rate"><span>LESSONS & MEMBERSHIPS</span><h3>Options coming soon</h3><p>Coaching packages and any membership offerings will be listed here.</p></div></div><div className="notice"><CalendarDays/><p><strong>Online reservations are not available yet.</strong> Booking instructions and payment options will appear here once confirmed.</p></div></div></section>
   <section className="section wrap" id="schedule"><div className="section-heading"><div><p className="eyebrow">ON THE CALENDAR</p><h2>Your next <em>good game.</em></h2></div></div><div className="schedule-row"><div className="date-tile"><CalendarDays/><span>TBA</span></div><div><span className="eyebrow">OPEN PLAY · LESSONS · EVENTS</span><h3>The next chapter is taking shape.</h3><p>Session dates, lessons, and community events will be announced here.</p></div><span className="status">Schedule coming soon</span></div></section>
   <section className="brand-art wrap"><img src="/images/wallpaper.jpg" alt="Pondview branded concept artwork featuring a covered pondside court and Rally, Recharge, Repeat slogan" loading="lazy"/><p>THE PONDVIEW VISION <span>Brand concept artwork · not a current facility photograph</span></p></section>
   <section className="section wrap visit-grid" id="visit"><div><p className="eyebrow">SEE YOU AT PONDVIEW</p><h2>A little escape.<br/><em>A great game.</em></h2><p className="visit-description">Pondview Pickleball Court<br/>Iba, Zambales, Philippines</p><div className="location-note"><MapPin/><p>Exact map pin and directions coming soon.</p></div></div><div className="visit-details"><div><Clock/><p><strong>Operating hours</strong><span>To be announced</span></p></div><div><CalendarDays/><p><strong>Opening & booking information</strong><span>Details to be confirmed</span></p></div><div><Users/><p><strong>Get in touch</strong><span>Phone, email, and Facebook links coming soon</span></p></div></div></section>
   <section className="faq wrap"><p className="eyebrow">BEFORE YOU VISIT</p><h2>A few helpful details.</h2><div>{[{q:'I’m new to pickleball. Can I learn at Pondview?',a:'Our team is RPO Pickleball Level 1 certified. Beginner lesson availability, rates, and schedules will be announced here.'},{q:'Are showers and bathrooms available?',a:'Yes. Pondview has shower and bathroom facilities on site, along with a shaded awning tent for breaks.'},{q:'Can I book a court online now?',a:'Online booking is not available yet. Rates, operating hours, and reservation instructions are placeholders until confirmed.'},{q:'Is equipment provided or available to rent?',a:'We have training equipment on site. Paddle rental prices and what is included with court bookings will be confirmed before reservations become available.'}].map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div></section>
  </main>
  <footer className="wrap"><a className="brand" href="#"><img src="/images/pondview-symbol.png" alt="Pondview logo"/><span>PONDVIEW<small>RALLY · RECHARGE · REPEAT</small></span></a><p>Iba, Zambales, Philippines</p><span>© {new Date().getFullYear()} Pondview Pickleball</span></footer>
 </>;
}
