import { Award, ShowerHead, Users, CalendarDays, Toilet, CircleDot, TreePalm } from 'lucide-react';
import { useState, type ImgHTMLAttributes } from 'react';
import { Header, Footer, InformationPage, Awning } from './Pages';

function Photo(props: ImgHTMLAttributes<HTMLImageElement>) { const [failed,setFailed]=useState(false); return failed ? <div className="photo-placeholder" role="img" aria-label={props.alt}><CircleDot/><span>Photo coming soon</span></div> : <img {...props} onError={()=>setFailed(true)}/>; }

const RECLUB_URL = 'https://reclub.co/clubs/@pondview-pickleball';

const activities = [
  { number:'01', title:'Your court. Your crew.', label:'COURT RENTALS', text:'Bring your friends and make time for a few good games.', rate:'Hourly rate to be announced', href:RECLUB_URL, action:'Schedule on Reclub' },
  { number:'02', title:'Meet your next doubles partner.', label:'OPEN PLAY', text:'A place to meet other players and share the court.', rate:'Sessions and player limits to be announced', href:RECLUB_URL, action:'Explore our Reclub' },
  { number:'03', title:'Build a better game.', label:'LESSONS & COACHING', text:'Learn with our RPO Pickleball Level 1 certified team.', rate:'Lesson formats and rates to be announced', href:'#coaching', action:'Meet the team' },
];
export default function Home() {
 const page = window.location.pathname.replace(/\/$/, "");
 if (page) return <><Header/><InformationPage page={page}/><Footer/></>;
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <Header/>
  <main id="main" className="home-main"><div className="palm-trail" aria-hidden="true"><TreePalm/><TreePalm/><TreePalm/></div>
   <section className="hero">
    <div className="hero-photo"><Photo src="/images/equipment.jpg" alt="Pickleball training equipment beside the pond at Pondview" fetchPriority="high"/></div>
    <div className="hero-shade"/>
    <div className="hero-copy wrap"><p className="eyebrow"><span/> IBA, ZAMBALES · PHILIPPINES</p><h1>Rally.<br/>Recharge.<br/><em>Repeat.</em></h1><p className="hero-description">Find your rhythm at Pondview.<br/>Pickleball, good company, and a little room to unwind.</p><div className="actions"><a className="button" href={RECLUB_URL}>Schedule on Reclub</a><a className="text-link" href="#facility">Explore Pondview</a></div></div>
    <div className="hero-bottom wrap"><span className="photo-caption">A glimpse of life at Pondview</span></div>
   </section>
   <div className="amenity-strip"><span><ShowerHead/> On-site showers</span><span><Toilet/> Bathroom facilities</span><span><Awning/> Covered Courts</span><span><CircleDot/> On-site training equipment</span></div>
   <section className="section wrap" id="play"><div className="section-heading"><div><p className="eyebrow">MAKE TIME FOR THE GAME</p><h2>A place for your<br/><em>kind of play.</em></h2></div><p>First rally or your favorite weekly ritual.<br/>Discover what’s taking shape at Pondview.</p></div><div className="play-grid">{activities.map(a=><article className="play-card" key={a.number}><h3>{a.label}</h3><p>{a.text}</p><div className="card-bottom"><small>{a.rate}</small><a className="text-link" href={a.href}>{a.action}</a></div></article>)}</div></section>
   <section className="coaching-section" id="coaching"><div className="wrap coaching-grid"><figure className="team-photo"><Photo src="/images/team.jpg" alt="Pondview representatives holding the club banner at the RPO training class" loading="lazy"/><figcaption>Pondview represented at RPO training</figcaption></figure><div className="coaching-copy"><p className="eyebrow">A STRONG FOUNDATION</p><h2>Passion for play.<br/><em>Commitment to learning.</em></h2><div className="certification"><Award size={76}/><div><strong>RPO Pickleball</strong><span>Level 1 certified</span></div></div><p>Our team brings RPO Pickleball Level 1 certification to Pondview, with a shared passion for helping more people enjoy the game.</p><p>New to pickleball? Start with the fundamentals and grow your confidence, one rally at a time.</p><a href={RECLUB_URL} className="button outline">Find sessions on Reclub</a></div></div><figure className="class-photo wrap"><Photo src="/images/class.jpg" alt="Participants and instructors in the RPO pickleball training class" loading="lazy"/><figcaption>Learning together. The RPO class community.</figcaption></figure></section>
   <section className="section wrap" id="facility"><div className="section-heading"><div><p className="eyebrow">BEYOND THE BASELINE</p><h2>Play. Take a breath.<br/><em>Stay a little longer.</em></h2></div><p>Practical comforts that make<br/>your time on site more enjoyable.</p></div><div className="facility-grid"><figure className="equipment-photo"><Photo src="/images/equipment.jpg" alt="Pondview’s current equipment including practice balls, a dink board, training targets, paddles, and a net" loading="lazy"/><figcaption>Our current on-site equipment</figcaption></figure><div className="amenities">{[{icon:ShowerHead,title:'Refresh after your game',text:'On-site shower facilities for a fresh start after a session.'},{icon:Toilet,title:'Bathroom facilities',text:'On-site bathrooms for your visit.'},{icon:Awning,title:'Covered Courts',text:'Enjoy your game on our covered courts.'},{icon:CircleDot,title:'More ways to practice',text:'On-site training equipment, including a dink board, practice balls, and targets. Usage details to be announced.'}].map(x=><div className="amenity" key={x.title}><x.icon/><div><h3>{x.title}</h3><p>{x.text}</p></div></div>)}</div></div></section>
   <section className="rates-section" id="rates"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">PLAN YOUR PLAY</p><h2>Good games.<br/><em>Clear details.</em></h2></div><p>Reclub is our main court scheduler.<br/>Check listings for schedules and booking details.</p></div><div className="rates-grid"><div className="rate"><span>PRIVATE COURT RENTAL</span><h3>Rates coming soon</h3><p>Hourly pricing, booking duration, and equipment inclusions will be listed here.</p></div><div className="rate"><span>OPEN PLAY</span><h3>Details coming soon</h3><p>Per-player pricing, skill groups, and session capacity will be listed here.</p></div><div className="rate"><span>LESSONS & MEMBERSHIPS</span><h3>Options coming soon</h3><p>Coaching packages and any membership offerings will be listed here.</p></div></div><div className="notice"><CalendarDays/><p><strong>Schedule your court time on Reclub.</strong> <a className="text-link" href={RECLUB_URL}>Visit the club page</a> for court schedules, posted sessions, and booking instructions.</p></div></div></section>
   <section className="section wrap" id="schedule"><div className="section-heading"><div><p className="eyebrow">OUR MAIN COURT SCHEDULER</p><h2>Your next <em>good game.</em></h2></div><p>Plan your next visit through Reclub.</p></div><div className="reclub-panel"><div className="reclub-copy"><span className="eyebrow">PONDVIEW PICKLEBALL</span><h3>Find your people.<br/>Make time to play.</h3><p>Find sessions on Reclub page to connect with the community and explore activities posted by Pondview.</p><a className="button" href={RECLUB_URL}>View court schedule on Reclub</a><small>Joining or signing up takes place on Reclub.</small></div><div className="reclub-details"><div><Users/><p><strong>Join the community</strong><span>Find Pondview Pickleball on Reclub.</span></p></div><div><CalendarDays/><p><strong>Check the court schedule</strong><span>Check the club page for posted sessions and event details.</span></p></div><div><CircleDot/><p><strong>Keep the details together</strong><span>Refer to each Reclub listing for its schedule and participation instructions.</span></p></div></div></div></section>
   <section className="brand-art wrap"><Photo src="/images/wallpaper.jpg" alt="Pondview branded concept artwork featuring a covered pondside court and Rally, Recharge, Repeat slogan" loading="lazy"/><p>THE PONDVIEW VISION <span>Brand concept artwork · not a current facility photograph</span></p></section>
   <section className="faq wrap"><p className="eyebrow">BEFORE YOU VISIT</p><h2>A few helpful details.</h2><div>{[{q:'I’m new to pickleball. Can I learn at Pondview?',a:'Our team is RPO Pickleball Level 1 certified. Beginner lesson availability, rates, and schedules will be announced here.'},{q:'Are showers and bathrooms available?',a:'Yes. Pondview has shower and bathroom facilities on site, along with covered courts.'},{q:'Can I book a court online now?',a:'Find sessions on Reclub page for posted activities and participation details. Private court rental booking is not enabled on this website; rates and reservation instructions are still to be confirmed.'},{q:'Is equipment provided or available to rent?',a:'We have training equipment on site. Paddle rental prices and what is included with court bookings will be confirmed before reservations become available.'}].map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div></section>
  </main>
  <Footer/>
 </>;
}
