import { Award, ShowerHead, Toilet, CircleDot, MapPin } from 'lucide-react';
import { ExternalLink, Photo, Awning, ScheduleButton, RECLUB, FACEBOOK, CONTACT_EMAIL } from './UI';
const rules = [
 ['Safety first','Safety is our first priority. Stop playing whenever an unsafe situation arises, such as a stray ball or a player getting injured. Warn adjacent courts if you hit a ball onto their court, and alert the Pondview team when someone needs help.'],
 ['Dress for safe play','Wear safe and proper attire, including shirts and non-marking shoes made for court sports. Proper eye protection is strongly recommended.'],
 ['Look after your guests','Accept responsibility for your guests and family members in attendance.'],
 ['Keep the court clear','Keep the court and surrounding play area clean and free of debris.'],
 ['Leave shared spaces clean','Clean up after yourself and your guests in café or social areas.'],
 ['Play with a clear head','Do not play if your movement or judgment is impaired by alcohol or other drugs.'],
 ['Choose the right level','When registering for leagues and tournaments, sign up for the appropriate level according to USA Pickleball standards. Pondview Pickleball reserves the right to move players to the proper competitive level of play.'],
 ['Show good sportsmanship','Always exhibit good sportsmanship when playing or spectating. Never direct any form of negativity or abuse at others.'],
 ['Respect the sound of the game','Portable speakers or music are not allowed in the club. Be considerate of the noise level when others are playing around you.'],
 ['Respect the equipment','Never throw your paddle or otherwise purposely mishandle any equipment.'],
 ['Encourage every player','Be respectful of players of lesser ability.'],
 ['Make fair line calls','Always strive to make correct line calls. If in doubt, you must call the ball in.'],
 ['Wait before entering','Never go onto a court while a point is in progress if you are not part of the game.'],
];
export const titles:Record<string,string>={'/play':'Play','/coach':'Meet the Coach','/facility':'Facility','/about':'About Us','/contact':'Contact Us','/code-of-conduct':'Code of Conduct','/thank-you':'Thank you'};
const reasons=['Media Inquiry','Donation / Sponsorship Request','Partnership','Questions','Concerns'];
const SKILL_MATRIX = 'https://usapickleball.org/docs/levels/Player-Skill-Level-Matrix.pdf';
const COURT_MAP = 'https://www.google.com/maps/place/PondView+Pickleball/@15.371219,119.9527521,1171m/data=!3m2!1e3!4b1!4m6!3m5!1s0x33943d003e67e713:0x6aea7d02de052ba5!8m2!3d15.371219!4d119.955327!16s%2Fg%2F11zf53f8b8?entry=ttu';
const faq=[
 ['I’m new to pickleball. Can I learn at Pondview?','Beginners are welcome! Coach Byron is RPO Pickleball Level 1 Certified. Check Reclub for posted sessions, or contact us about learning the basics.'],
 ['Are showers and bathrooms available?','Yes. At Pondview, shower and bathroom facilities are available on site, along with covered courts.'],
 ['How do I schedule court time?','Reclub is our main court scheduler. Check our club page for current sessions and booking details.'],
 ['How do I find my skill level?','Use the USA Pickleball Player Skill Level Matrix as a guide when choosing a session. If you are unsure, ask Coach Byron for help finding a suitable level.'],
 ['Are lockers available?','Public lockers are available on site. Let us know if you need somewhere to store your belongings. You don’t have to worry about your luggage while you’re here.'],
 ['Is equipment provided or available to rent?','We have training equipment on site. Contact us for current paddle availability and what is included with your session.'],
];
function Play(){return <><p className="eyebrow">MAKE TIME FOR THE GAME</p><h1>Your kind<br/><em>of play.</em></h1><p className="page-intro">Bring your friends, meet a new doubles partner, or work on your next great rally.</p><div className="play-grid">{[{title:'Court rentals',text:'Your court. Your crew. Make time for a few good games together.',detail:'Rental rates and inclusions coming soon.'},{title:'Open play',text:'Meet other players and share the court.',detail:'Check Reclub for posted sessions and player limits.'},{title:'Lessons and coaching',text:'Build your confidence with Coach Byron, RPO Pickleball Level 1 Certified.',detail:'Lesson formats and rates coming soon.'}].map(x=><article className="play-card" key={x.title}><h2>{x.title}</h2><p>{x.text}</p><div className="card-bottom"><small>{x.detail}</small>{x.title==='Lessons and coaching'?<a className="text-link" href="/coach/">Meet the Coach</a>:<ExternalLink className="text-link" href={RECLUB}>View on Reclub</ExternalLink>}</div></article>)}</div><div className="booking-note"><div><h2>Ready for your next game?</h2><p>Reclub is our main court scheduler.</p></div><ScheduleButton/></div></>;}
function Coach(){return <>
 <p className="eyebrow">MEET THE COACH</p><h1>Coach <em>Byron.</em></h1>
 <div className="coach-page-grid">
  <figure><Photo src="/images/byron-training.png" width={1364} height={1365} alt="Coach Byron in a white shirt and blue cap, holding a paddle and ball at RPO training"/></figure>
  <div className="coach-bio">
   <p className="coach-achievement"><Award size={21} aria-hidden="true"/><span>UAAP Table Tennis Silver Medalist</span></p>
   <p className="page-intro">Byron brought his college table tennis skills into professional pickleball.</p>
   <div className="certification"><Award size={76}/><div><strong>RPO Pickleball</strong><span>Level 1 Certified</span></div></div>
   <p>A UAAP table tennis silver medalist, Byron John Abuiza developed his game in college before bringing those skills into professional pickleball coaching.</p>
   <p>His background in timing, spin, and quick reactions shapes how he approaches the game. At Pondview, he pairs that experience with his RPO Pickleball Level 1 certification to help players build a strong foundation.</p>
   <p>Start with the fundamentals and build your confidence, one rally at a time.</p>
   <ExternalLink className="text-link" href="/images/byron-certificate.jpg">View certificate <span className="sr-only">(opens in a new tab)</span></ExternalLink>
   <div className="actions"><ScheduleButton/></div>
  </div>
 </div>
 <figure className="coach-training-full wrap"><Photo src="/images/class.jpg" width={2047} height={1143} alt="Coach Byron's RPO training class with participants and instructors" loading="lazy"/></figure>
</>;}
function Facility(){return <><p className="eyebrow">BEYOND THE BASELINE</p><h1>Room to play.<br/><em>Room to recharge.</em></h1><div className="facility-grid"><figure className="equipment-photo"><Photo src="/images/equipment.jpg" alt="Practice balls, training targets, paddles, net, and dink board at Pondview"/></figure><div className="amenities">{[{icon:Awning,title:'Covered Courts',text:'Enjoy your game on our covered courts.'},{icon:ShowerHead,title:'On-site showers',text:'Refresh after your session.'},{icon:Toilet,title:'Bathroom facilities',text:'On-site bathrooms for your visit.'},{icon:CircleDot,title:'Training equipment',text:'Practice balls, a dink board, and targets. Ask our team about equipment use.'}].map(x=><div className="amenity" key={x.title}><x.icon/><div><h2>{x.title}</h2><p>{x.text}</p></div></div>)}</div></div><section className="facility-faq" id="faq"><p className="eyebrow">BEFORE YOU VISIT</p><h2>A few helpful details.</h2><div className="faq-items">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p>{q==='How do I find my skill level?'&&<ExternalLink className="text-link" href={SKILL_MATRIX}>View player skill level matrix (PDF)</ExternalLink>}</details>)}</div></section><section className="area-map"><div><p className="eyebrow">FIND US IN ZAMBALES</p><h2>Pondview Pickleball</h2><p>9XC4+G7V<br/>Iba, Zambales, Philippines</p><ExternalLink className="text-link" href={COURT_MAP}><MapPin size={18}/>Get directions</ExternalLink></div><iframe title="Pondview Pickleball Court location in Iba, Zambales" src="https://maps.google.com/maps?q=15.371219%2C119.955327&z=17&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section></>;}
function Contact(){return <><p className="eyebrow">LET’S CONNECT</p><h1>Contact <em>Us.</em></h1><p className="page-intro">A question, an idea, or a way to grow the game together? We’d love to hear from you.</p><div className="contact-grid"><form action={`https://formsubmit.co/${CONTACT_EMAIL}`} method="POST"><input type="hidden" name="_subject" value="Pondview website inquiry"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_next" value={`${window.location.origin}/thank-you/`}/><input type="hidden" name="_url" value="https://pondviewpb.com/contact/"/><label className="form-trap" aria-hidden="true">Leave this field empty<input type="text" name="_honey" tabIndex={-1} autoComplete="off"/></label><label>Your name<input name="name" autoComplete="name" required maxLength={120}/></label><label>Your email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Reason for Contacting?<select name="reason" required defaultValue=""><option value="" disabled>Select a reason</option>{reasons.map(r=><option key={r}>{r}</option>)}</select></label><label>Tell us more<textarea name="message" rows={6} required maxLength={5000}/></label><p className="form-note">Your inquiry will be emailed to contact@pondviewpb.com. A quick verification may be required after you submit.</p><button className="button" type="submit">Submit</button></form><aside><h2>See you<br/><em>at Pondview.</em></h2><p>Iba, Zambales, Philippines</p><p><a className="text-link" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p><ExternalLink className="text-link" href={FACEBOOK}>Contact us on Facebook</ExternalLink><h3>Ready to play?</h3><p>Find court schedules and booking details on Reclub.</p><ScheduleButton className="button outline"/></aside></div></>;}
function About(){return <><p className="eyebrow">OUR STORY</p><h1>By Pickleballers.<br/><em>For Pickleballers.</em></h1><div className="story-page-grid"><figure className="story-photo"><Photo src="/images/team.jpg" width={1074} height={1018} alt="The Pondview team together at RPO training"/></figure><div className="story"><p className="page-intro">We believe a great game starts with a place where people feel welcome.</p><p>Pondview Pickleball grew from a simple desire: to share the game we love and make it easier for more people in the Philippines to pick up a paddle.</p><p>Here in Iba, Zambales, our goal is to create a welcoming space for first-time players, regular doubles partners, and everyone in between. We want learning the basics to feel approachable, finding a game to feel simple, and time on court to bring people together.</p><p>With RPO Pickleball Level 1 Certified coaching, every introduction to the game is a chance to build confidence, friendships, and a community that keeps coming back for another rally.</p><p>Making pickleball more accessible is an ongoing ambition. We’re starting with our court, our community, and the belief that there’s always room for one more player.</p><ScheduleButton/></div></div></>;}
function Conduct(){return <><p className="eyebrow">A GREAT GAME STARTS WITH RESPECT</p><h1>Code of <em>Conduct.</em></h1><p className="page-intro">Help us keep Pondview safe, welcoming, and enjoyable for every player and guest.</p><div className="conduct-list">{rules.map(([heading,text],i)=><section key={heading} className={i===0?'safety-priority':''}><h2>{heading}</h2><p>{text}</p>{heading==='Choose the right level'&&<ExternalLink className="text-link" href={SKILL_MATRIX}>USA Pickleball player skill level matrix (PDF)</ExternalLink>}</section>)}</div></>;}
export function InformationPage({page}:{page:string}){return <div className="wrap information-page">{page==='/play'?<Play/>:page==='/coach'?<Coach/>:page==='/facility'?<Facility/>:page==='/about'?<About/>:page==='/contact'?<Contact/>:page==='/code-of-conduct'?<Conduct/>:page==='/thank-you'?<><p className="eyebrow">THANK YOU FOR GETTING IN TOUCH</p><h1>See you <em>courtside.</em></h1><p className="page-intro">Thanks for your inquiry. If you need to follow up, email contact@pondviewpb.com.</p><a className="button" href="/">Return to Pondview</a></>:<><h1>Page not found.</h1><a className="button" href="/">Return to Pondview</a></>}</div>;}
