import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Menu, X, ArrowUpRight } from 'lucide-react';
const RECLUB = 'https://reclub.co/clubs/@pondview-pickleball';
const FACEBOOK = 'https://www.facebook.com/people/Pondview-Pickleball-Court/61593304634455/';
// Main public contact address, confirmed by the business owner.
export const CONTACT_EMAIL: string = 'support@pondviewpb.com';
export function Awning() { return <svg viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M3 19a13 13 0 0 1 26 0H3ZM5 19v10m22-10v10M12 19v10m8-10v10M2 29h28"/></svg>; }
export function Header() {
 const [open,setOpen]=useState(false); const toggle=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&open){setOpen(false);toggle.current?.focus();}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);
 return <header className="header"><a className="brand" href="/" aria-label="Pondview home"><img src="/images/pondview-symbol.png" alt=""/><span>PONDVIEW<small>PICKLEBALL COURT</small></span></a><button ref={toggle} className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav id="navigation" className={open?'is-open':''} aria-label="Main navigation" onClick={()=>setOpen(false)}><a href="/#play">Play</a><a href="/#coaching">Coaching</a><a href="/#facility">Facility</a><a href="/contact/">Contact Us</a><a className="mobile-schedule" href={RECLUB}>Schedule on Reclub</a></nav><a className="button small header-book" href={RECLUB}>Schedule on Reclub</a></header>;
}
export function Footer(){return <footer className="wrap site-footer"><a className="brand" href="/"><img src="/images/pondview-symbol.png" alt=""/><span>PONDVIEW<small>RALLY · RECHARGE · REPEAT</small></span></a><nav aria-label="Footer navigation"><a href="/about/">About Us</a><a href="/contact/">Contact Us</a><a href="/code-of-conduct/">Code of Conduct</a><a href={FACEBOOK}>Facebook</a><a href={RECLUB}>Reclub</a></nav><p className="footer-location">Iba, Zambales, Philippines</p><a className="text-link" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a><p className="copyright">© {new Date().getFullYear()} Pondview Pickleball</p></footer>;}
const rules = [
 ['Dress for safe play','Wear safe and proper attire, including shirts and non-marking shoes made for court sports. Proper eye protection is strongly recommended.'],
 ['Look after your guests','Accept responsibility for your guests and family members in attendance.'],
 ['Keep the court clear','Keep the court and surrounding play area clean and free of debris.'],
 ['Leave shared spaces clean','Clean up after yourself and your guests in café or social areas.'],
 ['Play with a clear head','Do not play if your movement or judgment is impaired by alcohol or other drugs.'],
 ['Choose the right level','When registering for leagues and tournaments, sign up for the appropriate level according to USA Pickleball standards. Pondview Pickleball reserves the right to move players to the proper competitive level of play.'],
 ['Show good sportsmanship','Always exhibit good sportsmanship when playing or spectating. Never direct any form of negativity or abuse at others.'],
 ['Respect the sound of the game','Portable speakers or music are not allowed in the club. Be considerate of the noise level when others are playing around you.'],
 ['Respect the equipment','Never throw your paddle or otherwise purposely mishandle any equipment.'],
 ['Encourage every player','Be respectful of players of lesser ability.'],
 ['Make fair line calls','Always strive to make correct line calls. If in doubt, you must call the ball in.'],
 ['Wait before entering','Never go onto a court while a point is in progress if you are not part of the game.'],
 ['Put safety first','Stop playing whenever an unsafe situation arises, such as a stray ball or a player getting injured. Do your best to warn adjacent courts if you hit a ball onto their court.'],
];
function Contact(){
 const [status,setStatus]=useState(''); const [draft,setDraft]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const subject=`Pondview inquiry: ${data.get('reason')}`;const body=`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nReason for contacting: ${data.get('reason')}\n\n${data.get('message')}`;
 if(CONTACT_EMAIL){window.location.href=`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setStatus('Your email app will open. Review and send your inquiry there.');return;}
 setDraft(body);try{await navigator.clipboard.writeText(body);setStatus('Inquiry copied—not sent. Open our Facebook page and paste it into a message.');}catch{setStatus('Your inquiry is ready below. Copy it and send it through our Facebook page.');}}
 return <><p className="eyebrow">LET’S CONNECT</p><h1>Contact <em>Us.</em></h1><p className="page-intro">A question, an idea, or a way to grow the game together? We’d love to hear from you.</p><div className="contact-grid"><form onSubmit={submit}><label>Your name<input name="name" autoComplete="name" required maxLength={120}/></label><label>Your email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Reason for Contacting?<select name="reason" required defaultValue=""><option value="" disabled>Select a reason</option>{['Franchise With Us','Media Inquiry','Donation / Sponsorship Request','Partnership','Questions','Concerns'].map(r=><option key={r}>{r}</option>)}</select></label><label>Tell us more<textarea name="message" rows={6} required maxLength={5000}/></label><p className="form-note">{CONTACT_EMAIL?'Opens a draft addressed to support@pondviewpb.com in your email app. Review it and press Send there.':'Email contact is coming soon. Copy your inquiry and send it to us on Facebook. This form does not send or store your message.'}</p><button className="button" type="submit">{CONTACT_EMAIL?'Compose email':'Copy inquiry'}</button><p role="status" className="form-status">{status}</p>{draft&&<label>Your inquiry<textarea readOnly rows={8} value={draft}/></label>}</form><aside><h2>See you<br/><em>at Pondview.</em></h2><p>Iba, Zambales, Philippines</p><p><a className="text-link" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p><a className="text-link" href={FACEBOOK}>Contact us on Facebook <ArrowUpRight size={16}/></a><h3>Ready to play?</h3><p>Reclub is our main court scheduler. Find court schedules and booking details on our club page.</p><a className="button outline" href={RECLUB}>Schedule on Reclub</a></aside></div></>;
}
export function InformationPage({page}:{page:string}){
 const title=page==='/about'?'About Us':page==='/contact'?'Contact Us':page==='/code-of-conduct'?'Code of Conduct':'Page not found';
 useEffect(()=>{document.title=`${title} | Pondview Pickleball`;},[title]);
 return <><a className="skip" href="#main">Skip to content</a><main id="main" className="wrap information-page">{page==='/about'?<><p className="eyebrow">OUR STORY</p><h1>By Pickleballers.<br/><em>For Pickleballers.</em></h1><div className="story"><p className="page-intro">We believe a great game starts with a place where people feel welcome.</p><p>Pondview Pickleball grew from a simple desire: to share the game we love and make it easier for more people in the Philippines to pick up a paddle.</p><p>Here in Iba, Zambales, our goal is to create a welcoming space for first-time players, regular doubles partners, and everyone in between. We want learning the basics to feel approachable, finding a game to feel simple, and time on court to bring people together.</p><p>Our RPO Pickleball Level 1 certified team shares that commitment to learning. Every introduction to the game is a chance to build confidence, friendships, and a community that keeps coming back for another rally.</p><p>Making pickleball more accessible is an ongoing ambition. We’re starting with our court, our community, and the belief that there’s always room for one more player.</p><a className="button" href={RECLUB}>Find your next game</a></div></>:page==='/contact'?<Contact/>:page==='/code-of-conduct'?<><p className="eyebrow">A GREAT GAME STARTS WITH RESPECT</p><h1>Code of <em>Conduct.</em></h1><p className="page-intro">Help us keep Pondview safe, welcoming, and enjoyable for every player and guest.</p><div className="conduct-list">{rules.map(([heading,text])=><section key={heading}><h2>{heading}</h2><p>{text}</p>{heading==='Choose the right level'&&<a className="text-link" href="https://usapickleball.org/wp-content/uploads/2020/07/USAPA-Skill-Rating-Definitions-2020.pdf">USA Pickleball skill-rating definitions (PDF, 2020)</a>}</section>)}</div></>:<><h1>Page not found.</h1><a className="button" href="/">Return to Pondview</a></>}</main></>;
}
