import { useEffect, useRef, useState, type AnchorHTMLAttributes, type ImgHTMLAttributes } from 'react';
import { Menu, X, CircleDot, TreePalm, Mail } from 'lucide-react';
function Facebook(){return <svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor" aria-hidden="true"><path d="M22 12a10 10 0 1 0-11.56 9.88v-6.99H7.9V12h2.54V9.8c0-2.51 1.49-3.9 3.77-3.9 1.09 0 2.23.2 2.23.2v2.46h-1.26c-1.24 0-1.62.77-1.62 1.56V12h2.77l-.44 2.89h-2.33v6.99A10 10 0 0 0 22 12Z"/></svg>;}
function Instagram(){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".7" fill="currentColor"/></svg>;}
export const RECLUB = 'https://reclub.co/clubs/@pondview-pickleball';
export const FACEBOOK = 'https://www.facebook.com/people/Pondview-Pickleball-Court/61593304634455/';
export const SUPPORT_EMAIL = 'support@pondviewpb.com';
export const CONTACT_EMAIL = 'contact@pondviewpb.com';
export function ExternalLink(props:AnchorHTMLAttributes<HTMLAnchorElement>){return <a {...props} target="_blank" rel="noopener noreferrer"/>;}
export function ReclubLogo(){return <span className="reclub-wordmark" role="img" aria-label="Reclub"/>;}
export function ScheduleButton({className='button'}:{className?:string}){return <ExternalLink className={`${className} schedule-button`} href={RECLUB}>Schedule on <ReclubLogo/><span className="sr-only"> (opens in a new tab)</span></ExternalLink>;}
export function Photo(props:ImgHTMLAttributes<HTMLImageElement>){const [failed,setFailed]=useState(false);return failed?<div className="photo-placeholder" role="img" aria-label={props.alt}><CircleDot/><span>Photo coming soon</span></div>:<img {...props} onError={()=>setFailed(true)}/>;}
export function Palms(){return <div className="palm-trail" aria-hidden="true"><TreePalm/><TreePalm/><TreePalm/></div>;}
export function Awning(){return <svg viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M3 19a13 13 0 0 1 26 0H3ZM5 19v10m22-10v10M12 19v10m8-10v10M2 29h28"/></svg>;}
export function Header({page}:{page:string}){
 const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&open){setOpen(false);toggle.current?.focus();}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);
 return <header className="header"><a className="brand" href="/" aria-label="Pondview home"><img src="/images/pondview-symbol.png" alt=""/><span>PONDVIEW<small>PICKLEBALL COURT</small></span></a><button ref={toggle} className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav id="navigation" className={open?'is-open':''} aria-label="Main navigation" onClick={()=>setOpen(false)}>{[['/play','Play'],['/coach','Coach'],['/facility','Facility'],['/contact','Contact']].map(([path,label])=><a key={path} href={`${path}/`} aria-current={page===path?'page':undefined}>{label}</a>)}<ScheduleButton className="mobile-schedule"/></nav><ScheduleButton className="button small header-book"/></header>;
}
export function Footer(){return <footer className="wrap site-footer"><a className="brand" href="/"><img src="/images/pondview-symbol.png" alt=""/><span>PONDVIEW<small>RALLY · RECHARGE · REPEAT</small></span></a><nav aria-label="Footer navigation"><a href="/about/">Our Story</a><a href="/contact/">Contact</a><a href="/facility/#faq">FAQs</a><a href="/code-of-conduct/">Code of Conduct</a></nav><div className="social-links" aria-label="Social media and email"><ExternalLink href={FACEBOOK} aria-label="Pondview on Facebook (opens in a new tab)" title="Facebook"><Facebook/></ExternalLink><span className="social-placeholder" role="img" aria-label="Instagram coming soon" title="Instagram coming soon"><Instagram/></span><ExternalLink href={RECLUB} aria-label="Pondview on Reclub (opens in a new tab)" title="Reclub"><span className="reclub-hand" aria-hidden="true"/></ExternalLink><a href={`mailto:${SUPPORT_EMAIL}`} aria-label="Email Pondview support" title={SUPPORT_EMAIL}><Mail aria-hidden="true"/></a></div><p className="footer-location">Iba, Zambales, Philippines</p><p className="copyright">© {new Date().getFullYear()} Pondview Pickleball</p></footer>;}
